apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "https://trace-api.newrelic.com/trace/v1?Api-Key=a8d372d51317868b0a0cfab0a5d4cd75FFFFNRAL&Data-Format=zipkin&Data-Format-Version=2"
